http:
  port: ${PORT}
apiEndpoints:
  auth:
    paths: ['/auth/login', '/auth/register']
  account:
    paths: ['/account/data', '/account/success-tutorial']
  profile:
    paths: ['/profile', '/profile/*', '/profile/information']
  activation:
    paths: ['/activation', '/activation/primary/*', '/activation/secondary/*']
  contact:
    paths:
      [
        '/contact',
        '/contact/me/app',
        '/contact/me/app/*',
        '/contact/me/list',
        '/contact/me/toggle',
        '/contact/me/sort',
      ]
  view:
    paths: '/view/*'
  use-link:
    paths: '/share/link/*'
  share:
    paths: ['/share/update', '/share/get']
  getRedirect:
    paths: '/device/scan/*'
  activate:
    paths: '/device/activate'
  getDeviceAll:
    paths: '/device/get-all'
  sendContact:
    paths: '/connection/send-contact'
  connection:
    paths:
      ['/connection/get-all-connect-list', '/connection/delete-connect-list/*']
serviceEndpoints:
  authService:
    url: http://service.tikcard.auth:3001
  profileService:
    url: http://service.tikcard.profile:3002
  deviceService:
    url: http://service.tikcard.device:3003
policies:
  - cors
  - proxy
  - authen
pipelines:
  authPipeline:
    apiEndpoints:
      - auth
    policies:
      - cors:
          - action:
              allowedHeaders: 'Content-Type'
      - proxy:
          - action:
              serviceEndpoint: authService
  accountPipeline:
    apiEndpoints:
      - account
    policies:
      - cors:
          - action:
              allowedHeaders: 'Content-Type, Authorization, profile'
      - proxy:
          - action:
              serviceEndpoint: authService
  profilePipeline:
    apiEndpoints:
      - profile
    policies:
      - cors:
          - action:
              allowedHeaders: 'Content-Type, Authorization, profile'
      - authen:
          - action:
              secretKey: ${SERVICE_PROFILE_SECRET_KEY}
      - proxy:
          - action:
              serviceEndpoint: profileService
  activationPipeline:
    apiEndpoints:
      - activation
    policies:
      - cors:
          - action:
              allowedHeaders: 'Content-Type, Authorization, profile'
      - authen:
          - action:
              secretKey: ${SERVICE_PROFILE_SECRET_KEY}
      - proxy:
          - action:
              serviceEndpoint: profileService
  contactPipeline:
    apiEndpoints:
      - contact
    policies:
      - cors:
          - action:
              allowedHeaders: 'Content-Type, Authorization, profile'
      - authen:
          - action:
              secretKey: ${SERVICE_PROFILE_SECRET_KEY}
      - proxy:
          - action:
              serviceEndpoint: profileService
  viewPipeline:
    apiEndpoints:
      - view
    policies:
      - cors:
          - action:
              allowedHeaders: 'Content-Type, Authorization, profile'
      - authen:
          - action:
              secretKey: ${SERVICE_PROFILE_SECRET_KEY}
      - proxy:
          - action:
              serviceEndpoint: profileService
  useLinkPipeline:
    apiEndpoints:
      - use-link
    policies:
      - cors:
          - action:
              allowedHeaders: 'Content-Type, Authorization, profile'
      - proxy:
          - action:
              serviceEndpoint: profileService
  sharePipeline:
    apiEndpoints:
      - share
    policies:
      - cors:
          - action:
              allowedHeaders: 'Content-Type, Authorization, profile'
      - authen:
          - action:
              secretKey: ${SERVICE_PROFILE_SECRET_KEY}
      - proxy:
          - action:
              serviceEndpoint: profileService
  getRedirectPipeline:
    apiEndpoints:
      - getRedirect
    policies:
      - cors:
          - action:
              allowedHeaders: 'Content-Type, Authorization, profile'
      - proxy:
          - action:
              serviceEndpoint: deviceService
  activatePipeline:
    apiEndpoints:
      - activate
    policies:
      - cors:
          - action:
              allowedHeaders: 'Content-Type, Authorization, profile'
      - authen:
          - action:
              secretKey: ${SERVICE_DEVICE_SECRET_KEY}
      - proxy:
          - action:
              serviceEndpoint: deviceService
  getDeviceAllPipeline:
    apiEndpoints:
      - getDeviceAll
    policies:
      - cors:
          - action:
              allowedHeaders: 'Content-Type, Authorization, profile'
      - authen:
          - action:
              secretKey: ${SERVICE_DEVICE_SECRET_KEY}
      - proxy:
          - action:
              serviceEndpoint: deviceService
  sendContactPipeline:
    apiEndpoints:
      - sendContact
    policies:
      - cors:
          - action:
              allowedHeaders: 'Content-Type, Authorization, profile'
      - proxy:
          - action:
              serviceEndpoint: profileService
  connectionPipeline:
    apiEndpoints:
      - connection
    policies:
      - cors:
          - action:
              allowedHeaders: 'Content-Type, Authorization, profile'
      - authen:
          - action:
              secretKey: ${SERVICE_PROFILE_SECRET_KEY}
      - proxy:
          - action:
              serviceEndpoint: profileService
